### ISSUE TITLE
how to send a data? 

### ISSUE THREAD

**Issue by bartzushka** [drsdre/yii2-wizardwidget#6]
i need to make a wizard with inputs  to make a survey. But i have a problem with submitting and sending data to the server. Maybe there is any trick or smth else.

**Comment by drsdre** [comment]
Hi,

In principle there are two approaches:
1. Server sided: on each step create a form with submit button (type=submit). On submit store the data with a controller function and render the wizard page again and add a GET 'step' parameter with the next page to render.
2. Client sided: Set up a form where the fields are fields across the steps. By default each step will have a previous/next button that switches between the steps. On the final step make sure to add a submit button which posts the complete form to the server.

Solution 1 has the advantage that form data is validated on each step but requires a bit more intelligence in the controller to determine what the next step is (and handle updated submits when user clicks previous step) . Solution 2 has the advantage that the user does not have to reload on each step, but disadvantage is that form validation by default happens on the last step and if a field on a previous page has errors this will not be immediately by clear (this can be somewhat fixed by showing all the error messages above the wizard also see for example http://yii2x.com/display-form-errors-errorsummary/).

Hope this helps a bit,
Andre

**Comment by bartzushka** [comment]
thx man! Im pretty new in web development.
The thing what confuse me is - that i need to make a functionality for administrator to create this forms with unlimited count of fields. 
I made the table of a Survey and a table of a SurveyQuestion and im using a CKEditor to create forms inside a surveyquestion create action. It displays the same i want but the problem is, that i need to confirm each step with creating a new SurveyUserAnswer, soo i need to pass some additional params into this widget is it possible? or maybe im loosing smth important. You dont have to tell me how to do that all, but if u can maybe u can give me some recommendations .

**Comment by bartzushka** [comment]
and the another question. Maybe i can use custom ajax request on each step to controller for submit the question  ? but in this way i need to send the id of a question which i have to pass into the widget

**Comment by drsdre** [comment]
If you have one question per wizard step which also is one record in the database, I would recommend to follow solution 2 (client sided) and setup on each step a submit button. See also the example I posted yesterday https://github.com/drsdre/yii2-wizardwidget/issues/2#issuecomment-151514280 in particular step 2 button definition.

**Comment by bartzushka** [comment]
Thx a lot man!) u saved me =) 
i decide my problem with your widget using ajax submit on each step.
The last question is. Is it real to disable navigation if the current step is  complete step ? 
oh yeah and i changed in css
.wizard li.active:after {
    left: 50%;
    transform: translateX(-50%);
}

**Comment by drsdre** [comment]
Regarding enabling and disabling navigation on steps, that would be up to how you decide to interact with the user. Implementing this will have to be done using javascript onclick events.

The CSS change is indeed more predictable than current method
