### ISSUE TITLE
Pjax updated step content disables buttons

### ISSUE THREAD

**Issue by robov** [drsdre/yii2-wizardwidget#8]
It seems that when I reload the widget with pjax, the step buttons are no longer working
I encapsulated the entire widget in pjax with an external form to update the data...
This works all very nicely... however the back/ forward buttons no longer work
Am I overlooking somehting ?

**Comment by drsdre** [comment]
Can you show some code on what you are trying to do?

**Comment by robov** [comment]
The code is no longer active...
But bsically it was something like this

$currentstep (passed in to the rendering of this page)

$step2 = <get ajax content>

Widget
Step2 = $step2
Step2 = $step3 
Active step = $currentstep

**Comment by 3dgroup** [comment]
I believe this can be fixed by changing the jQuery events from:

$(".next-step").click(function (e) {
to
$(document).on("click", ".next-step", function (e) {

I am loading this wizard in a bootstrap model, at each step i have a form that needs submitting, i submit via Ajax and then the content in the bootstrap model reloads. The buttons are then broken, switching the jquery events should resolve this.

**Comment by drsdre** [comment]
Thanks for the fix. I've applied the fix in the latest master branch version. After some testing, I will package the fix in a minor release.
